// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sakanak.DAL.Contexts;

#nullable disable

namespace Sakanak.DAL.Migrations
{
    [DbContext(typeof(SakanakDbContext))]
    [Migration("20260417044759_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChatUser", b =>
                {
                    b.Property<int>("ChatsChatID")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantsUserID")
                        .HasColumnType("int");

                    b.HasKey("ChatsChatID", "ParticipantsUserID");

                    b.HasIndex("ParticipantsUserID");

                    b.ToTable("ChatParticipants", (string)null);
                });

            modelBuilder.Entity("ContractStudent", b =>
                {
                    b.Property<int>("ContractsContractID")
                        .HasColumnType("int");

                    b.Property<int>("StudentsUserID")
                        .HasColumnType("int");

                    b.HasKey("ContractsContractID", "StudentsUserID");

                    b.HasIndex("StudentsUserID");

                    b.ToTable("ContractStudents", (string)null);
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Apartment", b =>
                {
                    b.Property<int>("ApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApartmentID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LandlordID")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<string>("VirtualTourURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ApartmentID");

                    b.HasIndex("LandlordID");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.ApartmentGroup", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupID"));

                    b.Property<int>("ApartmentID")
                        .HasColumnType("int");

                    b.Property<int>("CurrentMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("GroupStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.HasKey("GroupID");

                    b.HasIndex("ApartmentID")
                        .IsUnique();

                    b.ToTable("ApartmentGroups");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<int>("ApartmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("ApartmentID");

                    b.HasIndex("StudentID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Chat", b =>
                {
                    b.Property<int>("ChatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatID"));

                    b.Property<int?>("ApartmentGroupID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ChatID");

                    b.HasIndex("ApartmentGroupID")
                        .IsUnique()
                        .HasFilter("[ApartmentGroupID] IS NOT NULL");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Contract", b =>
                {
                    b.Property<int>("ContractID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractID"));

                    b.Property<int>("ApartmentID")
                        .HasColumnType("int");

                    b.Property<string>("ContractStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LandlordID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifiedByAdminID")
                        .HasColumnType("int");

                    b.HasKey("ContractID");

                    b.HasIndex("ApartmentID")
                        .IsUnique();

                    b.HasIndex("LandlordID");

                    b.HasIndex("VerifiedByAdminID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.LifestyleQuestionnaire", b =>
                {
                    b.Property<int>("QuestionnaireID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionnaireID"));

                    b.Property<string>("GenderPreference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HygieneLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsSmoker")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("SleepSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialPreference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("StudyHabits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionnaireID");

                    b.HasIndex("StudentID")
                        .IsUnique();

                    b.ToTable("LifestyleQuestionnaires");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<int>("ChatID")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("SenderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageID");

                    b.HasIndex("ChatID");

                    b.HasIndex("SenderID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApartmentID")
                        .HasColumnType("int");

                    b.Property<int>("LandlordID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("LandlordID");

                    b.HasIndex("StudentID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Penalty", b =>
                {
                    b.Property<int>("PenaltyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PenaltyID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IssuedByAdminID")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("PenaltyID");

                    b.HasIndex("IssuedByAdminID");

                    b.HasIndex("StudentID");

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.RoommateRating", b =>
                {
                    b.Property<int>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RatedStudentID")
                        .HasColumnType("int");

                    b.Property<int>("RaterStudentID")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("RatingID");

                    b.HasIndex("RatedStudentID");

                    b.HasIndex("RaterStudentID", "RatedStudentID")
                        .IsUnique();

                    b.ToTable("RoommateRatings");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Admin", b =>
                {
                    b.HasBaseType("Sakanak.Domain.Entities.User");

                    b.Property<string>("RoleLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Landlord", b =>
                {
                    b.HasBaseType("Sakanak.Domain.Entities.User");

                    b.Property<int>("TotalProperties")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("VerificationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasDiscriminator().HasValue("Landlord");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Student", b =>
                {
                    b.HasBaseType("Sakanak.Domain.Entities.User");

                    b.Property<int?>("ApartmentGroupID")
                        .HasColumnType("int");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LatePaymentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasIndex("ApartmentGroupID");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("ChatUser", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Chat", null)
                        .WithMany()
                        .HasForeignKey("ChatsChatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sakanak.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractStudent", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractsContractID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sakanak.Domain.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Apartment", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Landlord", "Landlord")
                        .WithMany("Apartments")
                        .HasForeignKey("LandlordID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.ApartmentGroup", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Apartment", "Apartment")
                        .WithOne("ApartmentGroup")
                        .HasForeignKey("Sakanak.Domain.Entities.ApartmentGroup", "ApartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Apartment", "Apartment")
                        .WithMany("Bookings")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakanak.Domain.Entities.Student", "Student")
                        .WithMany("Bookings")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Chat", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.ApartmentGroup", "ApartmentGroup")
                        .WithOne("Chat")
                        .HasForeignKey("Sakanak.Domain.Entities.Chat", "ApartmentGroupID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApartmentGroup");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Contract", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Apartment", "Apartment")
                        .WithOne("Contract")
                        .HasForeignKey("Sakanak.Domain.Entities.Contract", "ApartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakanak.Domain.Entities.Landlord", "Landlord")
                        .WithMany("Contracts")
                        .HasForeignKey("LandlordID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakanak.Domain.Entities.Admin", "VerifiedByAdmin")
                        .WithMany("VerifiedContracts")
                        .HasForeignKey("VerifiedByAdminID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Apartment");

                    b.Navigation("Landlord");

                    b.Navigation("VerifiedByAdmin");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.LifestyleQuestionnaire", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Student", "Student")
                        .WithOne("LifestyleQuestionnaire")
                        .HasForeignKey("Sakanak.Domain.Entities.LifestyleQuestionnaire", "StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Message", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakanak.Domain.Entities.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Landlord", "Landlord")
                        .WithMany("PaymentsReceived")
                        .HasForeignKey("LandlordID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakanak.Domain.Entities.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Landlord");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Penalty", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Admin", "IssuedByAdmin")
                        .WithMany("IssuedPenalties")
                        .HasForeignKey("IssuedByAdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakanak.Domain.Entities.Student", "Student")
                        .WithMany("Penalties")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IssuedByAdmin");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.RoommateRating", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Student", "RatedStudent")
                        .WithMany("RatingsReceived")
                        .HasForeignKey("RatedStudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakanak.Domain.Entities.Student", "RaterStudent")
                        .WithMany("RatingsGiven")
                        .HasForeignKey("RaterStudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RatedStudent");

                    b.Navigation("RaterStudent");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Student", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.ApartmentGroup", "ApartmentGroup")
                        .WithMany("Students")
                        .HasForeignKey("ApartmentGroupID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApartmentGroup");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Apartment", b =>
                {
                    b.Navigation("ApartmentGroup");

                    b.Navigation("Bookings");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.ApartmentGroup", b =>
                {
                    b.Navigation("Chat");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("SentMessages");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Admin", b =>
                {
                    b.Navigation("IssuedPenalties");

                    b.Navigation("VerifiedContracts");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Landlord", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("Contracts");

                    b.Navigation("PaymentsReceived");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Student", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("LifestyleQuestionnaire");

                    b.Navigation("Payments");

                    b.Navigation("Penalties");

                    b.Navigation("RatingsGiven");

                    b.Navigation("RatingsReceived");
                });
#pragma warning restore 612, 618
        }
    }
}
