// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sakanak.DAL.Data;

#nullable disable

namespace Sakanak.DAL.Migrations
{
    [DbContext(typeof(SakanakDbContext))]
    partial class SakanakDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("UserIdSeq");

            modelBuilder.Entity("ContractStudent", b =>
                {
                    b.Property<int>("ContractsContractId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsUserId")
                        .HasColumnType("int");

                    b.HasKey("ContractsContractId", "StudentsUserId");

                    b.HasIndex("StudentsUserId");

                    b.ToTable("ContractStudents", (string)null);
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Apartment", b =>
                {
                    b.Property<int>("ApartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApartmentId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LandlordId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<string>("VirtualTourUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ApartmentId");

                    b.HasIndex("LandlordId");

                    b.HasIndex("City", "IsActive");

                    b.HasIndex("PricePerMonth", "IsActive");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.ApartmentGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<string>("GroupStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ApartmentId", "GroupStatus")
                        .IsUnique()
                        .HasFilter("[GroupStatus] = 'Open'");

                    b.ToTable("ApartmentGroups");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int?>("ApartmentGroupId")
                        .HasColumnType("int");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("ApartmentGroupId");

                    b.HasIndex("ApartmentId", "Status");

                    b.HasIndex("StudentId", "Status");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VerifiedByAdminId")
                        .HasColumnType("int");

                    b.HasKey("ContractId");

                    b.HasIndex("BookingId");

                    b.HasIndex("EndDate");

                    b.HasIndex("VerifiedByAdminId");

                    b.HasIndex("ApartmentId", "Status");

                    b.HasIndex("LandlordId", "Status");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.LifestyleQuestionnaire", b =>
                {
                    b.Property<int>("QuestionnaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionnaireId"));

                    b.Property<string>("GenderPreference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HygieneLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsSmoker")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("SleepSchedule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SocialPreference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudyHabits")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("QuestionnaireId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("LifestyleQuestionnaires");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Media", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LandlordUserId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentUserId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MediaId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ContractId");

                    b.HasIndex("LandlordUserId");

                    b.HasIndex("StudentUserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("EntityType", "EntityId", "Type");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ContractId");

                    b.HasIndex("DueDate", "Status");

                    b.HasIndex("LandlordId", "Status");

                    b.HasIndex("StudentId", "Status");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LandlordId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RequestId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ContractId");

                    b.HasIndex("LandlordId", "Status");

                    b.HasIndex("StudentId", "Status");

                    b.HasIndex("Type", "Status");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR UserIdSeq");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Admin", b =>
                {
                    b.HasBaseType("Sakanak.Domain.Entities.User");

                    b.Property<string>("RoleLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleLevel");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Landlord", b =>
                {
                    b.HasBaseType("Sakanak.Domain.Entities.User");

                    b.Property<int>("TotalProperties")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("VerificationStatus")
                        .HasColumnType("bit");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("VerificationStatus");

                    b.ToTable("Landlords", (string)null);
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Student", b =>
                {
                    b.HasBaseType("Sakanak.Domain.Entities.User");

                    b.Property<int?>("ApartmentGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LatePaymentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasIndex("ApartmentGroupId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("ContractStudent", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractsContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sakanak.Domain.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Apartment", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Landlord", "Landlord")
                        .WithMany("Apartments")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.ApartmentGroup", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Apartment", "Apartment")
                        .WithMany("ApartmentGroups")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.ApartmentGroup", "ApartmentGroup")
                        .WithMany("Bookings")
                        .HasForeignKey("ApartmentGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sakanak.Domain.Entities.Apartment", "Apartment")
                        .WithMany("Bookings")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakanak.Domain.Entities.Student", "Student")
                        .WithMany("Bookings")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("ApartmentGroup");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Contract", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Apartment", "Apartment")
                        .WithMany("Contracts")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakanak.Domain.Entities.Booking", "Booking")
                        .WithMany("Contracts")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakanak.Domain.Entities.Landlord", "Landlord")
                        .WithMany("Contracts")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakanak.Domain.Entities.Admin", "VerifiedByAdmin")
                        .WithMany("VerifiedContracts")
                        .HasForeignKey("VerifiedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Apartment");

                    b.Navigation("Booking");

                    b.Navigation("Landlord");

                    b.Navigation("VerifiedByAdmin");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.LifestyleQuestionnaire", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Student", "Student")
                        .WithOne("Questionnaire")
                        .HasForeignKey("Sakanak.Domain.Entities.LifestyleQuestionnaire", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Media", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Apartment", null)
                        .WithMany("Media")
                        .HasForeignKey("ApartmentId");

                    b.HasOne("Sakanak.Domain.Entities.Contract", null)
                        .WithMany("Media")
                        .HasForeignKey("ContractId");

                    b.HasOne("Sakanak.Domain.Entities.Landlord", null)
                        .WithMany("Media")
                        .HasForeignKey("LandlordUserId");

                    b.HasOne("Sakanak.Domain.Entities.Student", null)
                        .WithMany("Media")
                        .HasForeignKey("StudentUserId");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakanak.Domain.Entities.Contract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sakanak.Domain.Entities.Landlord", "Landlord")
                        .WithMany("Payments")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakanak.Domain.Entities.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Contract");

                    b.Navigation("Landlord");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Request", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.Apartment", "Apartment")
                        .WithMany("Requests")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sakanak.Domain.Entities.Contract", "Contract")
                        .WithMany("Requests")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sakanak.Domain.Entities.Landlord", "Landlord")
                        .WithMany("Requests")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sakanak.Domain.Entities.Student", "Student")
                        .WithMany("Requests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Apartment");

                    b.Navigation("Contract");

                    b.Navigation("Landlord");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Student", b =>
                {
                    b.HasOne("Sakanak.Domain.Entities.ApartmentGroup", "ApartmentGroup")
                        .WithMany("Students")
                        .HasForeignKey("ApartmentGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApartmentGroup");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Apartment", b =>
                {
                    b.Navigation("ApartmentGroups");

                    b.Navigation("Bookings");

                    b.Navigation("Contracts");

                    b.Navigation("Media");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.ApartmentGroup", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Payments");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Admin", b =>
                {
                    b.Navigation("VerifiedContracts");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Landlord", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("Contracts");

                    b.Navigation("Media");

                    b.Navigation("Payments");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Sakanak.Domain.Entities.Student", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Media");

                    b.Navigation("Payments");

                    b.Navigation("Questionnaire");

                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
